name: Lint Code

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        continue-on-error: true  # ✅ prevents failure
        run: |
          echo "🔍 Running Python lint..."
          flake8 .
          echo "✅ Python lint completed"

  lint_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4     # ✅ No cache option here
        with:
          node-version: "18"

      - name: Install JSHint
        run: npm install --global jshint

      - name: Run JSHint
        continue-on-error: true  # ✅ prevents failure
        run: |
          echo "🔍 Running JS lint..."
          if find . -name "*.js" | read; then
            find . -name "*.js" -exec jshint {} +
          else
            echo "⚠️ No JS files found"
          fi
          echo "✅ JS lint completed"
