name: Lint Code

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          echo "Running Python linter..."
          flake8 .
          echo "✅ Python linting completed"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"   # Node 14 is deprecated

      - name: Install JSHint
        run: npm install --global jshint

      - name: Run JSHint
        run: |
          echo "Running JavaScript linter..."
          if find ./server/database -name "*.js" | read; then
            find ./server/database -name "*.js" -exec jshint {} +
            echo "✅ JavaScript linting completed"
          else
            echo "⚠️ No JS files found in ./server/database"
          fi
